# Generated by Django 3.2.5 on 2021-09-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0003_auto_20210921_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lnmonline',
            name='MerchantRequestID',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
